abbr g git
abbr ga 'git add'
abbr gaa 'git add --all .'
abbr gba 'git branch -a'
abbr gbd! 'git branch -D'
abbr gca! 'git commit -v -a --amend'
abbr gci 'git commit -v'
abbr gco 'git checkout'
abbr gcob 'git checkout -b'
abbr gcot 'git checkout -t'
abbr gd 'git diff -M'
abbr gddv 'git diff develop'
abbr gdm 'git diff master'
abbr gl 'git pull'
abbr glg 'git log --stat'
abbr glgs 'git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative | more -r'
abbr glr 'git pull --rebase'
abbr gm! 'git merge'
abbr gp 'git push'
abbr gpt 'git push --tags'
abbr gs 'git status'
abbr gst 'git status'
abbr gwip 'git add --all; git commit -am "WIP"'
